### ISSUE TITLE
Driver _support() function returning false every time.

### ISSUE THREAD

**Issue by JeffreyJamesAttenti** [thgreasi/localForage-cordovaSQLiteDriver#1]
The driver isn't working for me and I think I may know why but need help. It appears that the code being executed in the deviceReady promise is checking for globalObject.sqlitePlugin before device ready is emitted by cordova. 

I'm getting the same behavior on an emulator with Android 4.4.2 and an Android device 5.0.1.

I'm using angular-localforage as well and first tried configuring the driver by within the config() function for my app's main module like so:

```
  $localForageProvider.config({
      driver: [window.cordovaSQLiteDriver._driver, localforage.INDEXEDDB]
      name: 'localData'
  });
```

I then tried configuring it per the example in the repo's readme but called it in a deviceReady handler which is defined in the module's run()  function, like this:

```
    localforage.defineDriver(window.cordovaSQLiteDriver).then(
      function () {
        return localforage.setDriver([
            window.cordovaSQLiteDriver._driver,
            localforage.INDEXEDDB
        ]);
      },
      function (error) {
        console.error(error);
      }
    );
```

It falls back to the indexedDB driver because _support() is returning false from this driver. Is there anything else I could try or is this a bug?

**Comment by thgreasi** [comment]
[Here is an example Ionic app ](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) that I used for my tests. It runs on the emulator and on my LG G3.
As you can [see](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/www/index.html), there is not need to wait for Cordova events, since [the library does that for you already](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/blob/master/src/localforage-cordovasqlitedriver.js#L51-L60).

**Comment by JeffreyJamesAttenti** [comment]
Ok I found my problem and it was luckily a simple one. cordova.js was linked after the driver's js file and that's why it didn't find globalObject.cordova while the deviceReady promise code executed. 

Sorry about the false alarm.

**Comment by thgreasi** [comment]
Happy I could help and that somebody found this repo useful!
